# Clash 配置（适用于 Clash Meta/基础版）
# 使用 Shadowsocks IP 直连 VPS 多端口，自动测速选择最低延迟

mixed-port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: rule
log-level: info
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  fallback:
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query

proxies:
  - name: "SS-50314"
    type: ss
    server: 103.115.18.11
    port: 50314
    cipher: chacha20-ietf-poly1305
    password: ILoveLiuShuHan

  - name: "SS-50315"
    type: ss
    server: 103.115.18.11
    port: 50315
    cipher: chacha20-ietf-poly1305
    password: ILoveLiuShuHan

  - name: "SS-50316"
    type: ss
    server: 103.115.18.11
    port: 50316
    cipher: chacha20-ietf-poly1305
    password: ILoveLiuShuHan

  - name: "SS-50317"
    type: ss
    server: 103.115.18.11
    port: 50317
    cipher: chacha20-ietf-poly1305
    password: ILoveLiuShuHan

  - name: "SS-50318"
    type: ss
    server: 103.115.18.11
    port: 50318
    cipher: chacha20-ietf-poly1305
    password: ILoveLiuShuHan

  - name: "SS-50319"
    type: ss
    server: 103.115.18.11
    port: 50319
    cipher: chacha20-ietf-poly1305
    password: ILoveLiuShuHan

  - name: "SS-50320"
    type: ss
    server: 103.115.18.11
    port: 50320
    cipher: chacha20-ietf-poly1305
    password: ILoveLiuShuHan

  - name: "SS-50321"
    type: ss
    server: 103.115.18.11
    port: 50321
    cipher: chacha20-ietf-poly1305
    password: ILoveLiuShuHan

  - name: "SS-50322"
    type: ss
    server: 103.115.18.11
    port: 50322
    cipher: chacha20-ietf-poly1305
    password: ILoveLiuShuHan

  - name: "SS-50323"
    type: ss
    server: 103.115.18.11
    port: 50323
    cipher: chacha20-ietf-poly1305
    password: ILoveLiuShuHan

proxy-groups:
  - name: "AutoSelect"
    type: url-test
    proxies:
      - SS-50314
      - SS-50315
      - SS-50316
      - SS-50317
      - SS-50318
      - SS-50319
      - SS-50320
      - SS-50321
      - SS-50322
      - SS-50323
    url: "https://speed.cloudflare.com/__down?bytes=10000000"
    interval: 300   # ← 这里单位是“秒”，300秒 = 5分钟

  - name: "Smart-load"
    type: load-balance
    proxies:
      - SS-50314
      - SS-50315
      - SS-50316
    strategy: round-robin
    url: "https://www.youtube.com"
    interval: 300

  - name: "ChatGPT"
    type: url-test
    proxies:
      - SS-50314
      - SS-50315
      - SS-50316
      - SS-50317
      - SS-50318
      - SS-50319
      - SS-50320
      - SS-50321
      - SS-50322
      - SS-50323
    url: "https://chatgpt.com"
    interval: 300   # ← 这里单位是“秒”，300秒 = 5分钟

  - name: "SelectManually"
    type: select
    proxies:
      - AutoSelect
      - Smart-load
      - ChatGPT
      - SS-50314
      - SS-50315
      - SS-50316
      - SS-50317
      - SS-50318
      - SS-50319
      - SS-50320
      - SS-50321
      - SS-50322
      - SS-50323
      - DIRECT

rules:
  # 国内常用网站走直连
  - DOMAIN-SUFFIX,bilibili.com,DIRECT
  - DOMAIN-SUFFIX,iqiyi.com,DIRECT
  - DOMAIN-SUFFIX,acfun.cn,DIRECT
  - DOMAIN-SUFFIX,zhihu.com,DIRECT
  - DOMAIN-SUFFIX,bytedance.com,DIRECT
  - DOMAIN-SUFFIX,douyin.com,DIRECT
  - DOMAIN-SUFFIX,163.com,DIRECT
  - DOMAIN-SUFFIX,alicdn.com,DIRECT
  - DOMAIN-SUFFIX,alipay.com,DIRECT
  - DOMAIN-SUFFIX,taobao.com,DIRECT
  - DOMAIN-SUFFIX,weibo.com,DIRECT
  - DOMAIN-SUFFIX,qq.com,DIRECT
  - DOMAIN-SUFFIX,mi.com,DIRECT

  # 常用加速应用（可按需添加）
  - DOMAIN-SUFFIX,youtube.com,SelectManually
  - DOMAIN-SUFFIX,ytimg.com,SelectManually
  - DOMAIN-SUFFIX,telegram.org,SelectManually
  - DOMAIN-SUFFIX,t.me,SelectManually
  - DOMAIN-SUFFIX,openai.com,SelectManually
  - DOMAIN-SUFFIX,chatgpt.com,SelectManually

  # 其他国外默认走 AutoSelect
  - GEOIP,CN,DIRECT
  - MATCH,SelectManually
